apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: registry.local:5000/client
      ports:
        - containerPort: 3000
